General:
  ENVIRONMENT: test
  
  
METERING:
  latitude: 45.02776967279967
  longitude: 7.639643285417048
  VOLTAGE_COEFF: 520
  CURRENT_COEFF: 25000
  MOVING_AVG_LEN: 5
  
CONTROL:
  sampling_rate: 0.1
  send_batch_size: 1
  raw_batch_size: 20
  KP:
  KD:
  SAMPLING_DIVIDER: 200
  THRESHOLD: 10

DATABASE:
  USERNAME: admin
  PASSWORD: password
  HOST: '130.192.92.239'
  PORT: '27020'
  DB: mongodb

COMMUNICATION:
  CLOUD:
    PROTOCOL: http
    SERVER: 'watt.linksfoundation.com'
    PORT: 8080
    TOKEN: 's2PUxOTsaqGbSeSxq9AV'
  LOCAL:
    PROTOCOL: mqtt
    SERVER: '127.0.0.1'
    PORT: 1883
  SETPOINTS:
    PROTOCOL: mqtt
    SERVER: '130.192.92.239'
    PORT: 1882
    TOPIC: 'incitev/uc4/smartcharging/setpoint/cs1'
