
METERING:
  ENVIRONMENT: test
  latitude: 45.02776967279967
  longitude: 7.639643285417048


CONTROL:
  sampling_rate: 0.1
  send_batch_size: 1
  raw_batch_size: 100
  KP:
  KD:

DATABASE:
  USERNAME: admin
  PASSWORD: password
  HOST: '130.192.92.239'
  PORT: '27020'
  DB: mongodb

COMMUNICATION:
  CLOUD:
    PROTOCOL: http
    SERVER: 'watt.linksfoundation.com'
    PORT: 8080
    TOKEN: 's2PUxOTsaqGbSeSxq9AV'
  LOCAL:
    PROTOCOL: mqtt
    SERVER: '127.0.0.1'
    PORT: 1883
  SETPOINTS:
    PROTOCOL: mqtt
    SERVER: '130.192.92.239'
    PORT: 1882
    TOPIC: 'incitev/uc4/smartcharging/setpoint/cs1'
